### ISSUE TITLE
Suggestions CVARs and API

### ISSUE THREAD

**Issue by Graffiti007** [dataviruset/sm-hosties#21]
Need CVARs enable/disable for each LR in SM_Hosties. Example, some types Knife Fight LR is not working on CSGO, and the menu entries are not needed.

And it would be good to do API for adding new types Knife Fight, example, 50 HP.

**Comment by DorCoMaNdO** [comment]
We plan to eventually "ship" SM_Hosties as an API library and all the LRs will be added as plugins, just like custom LRs.

**Comment by PreFix** [comment]
Finnaly it will happen! yey! thanks for letting us to know DorCoMaNdO!

**Comment by data-bomb** [comment]
There are some Knife Fights like Drugs and Drunk that are not working on CS:GO currently.  I will go through and add checks for CS:GO since there are no similar effects available in CS:GO files.  We'd like for all LRs to be outside Hosties entirely but right now it's too much work for a community that is very small.

**Comment by data-bomb** [comment]
https://github.com/dataviruset/sm-hosties/commit/a4e4af6166c61ce430b6ad3e3f82a3671fc8d400 fixes the only bug noted here on CS:GO knife fights not working.  The rest are feature requests and will not be assigned at this time.
