### ISSUE TITLE
Last Request Mag4Mag

### ISSUE THREAD

**Issue by Caaine** [dataviruset/sm-hosties#64]
Weapon: Glock-18
Bug: When emptying the Glock-18 with right-click, while Mag4Mag gets the next player no shots.

SourceMod 1.8.0.5954
"SM_Hosties v2" (2.2.3) by databomb & dataviruset & comando

greetz
Caaine

**Comment by data-bomb** [comment]
Request additional details.  Unable to understand the entry conditions required for this to happen beyond waiting a long time before shooting.  Burst fire is toggled using right-click on the Glock.  

Currently when the Mag4Mag LR is initialized the right-click is disabled for 5000 ticks.  Additionally, after each shot the right-click is disabled for another 5000 ticks.

Please confirm that the entrance condition to this bug is waiting some period of time after the LR is initialized before right-click is enabled.  Record the amount of time needed before right-click is possible using a stopwatch and also the tick value for the server experiencing the issue.

Sent from my iPhone

**Comment by Waky-mKy** [comment]
Hi I can confirm Caaine´s request. The right-click is instantly useable and your Mag4mag partner is not receiving ammo. My server is only running the latest version of sourcemod and Hosties.

**Comment by data-bomb** [comment]
@Caaine Could you test the beta branch and let us know if this fixed the problem?

**Comment by Caaine** [comment]
The Secondary Attack is disabled? right? for me it's fine :D

**Comment by data-bomb** [comment]
Yes, secondary attack is now disabled during Mag4Mag LR. Glad it fixed it! Can finally close this one (-:
